### ISSUE TITLE
The server could not be started

### ISSUE THREAD

**Issue by JackMeds** [KettleFoundation/Kettle#15] opened 2019-02-28 00:46 UTC
The server could not be started
[log](https://pastebin.com/Jam1jv8u)
Seems to be an issue with applecore

**Comment by josephworks** [comment] 2019-02-28 05:04
Here are the technical issues:
java.lang.NoClassDefFoundError: net/minecraft/block/BlockCake
java.lang.ClassNotFoundException: net.minecraft.block.BlockCake

The issue is because of the BlockCake class is missing.
Does that mean that cake doesn't work in kettle

**Comment by josephworks** [comment] 2019-02-28 05:07
**I have a fix for @aolko @Hexeption !!!
copy or rename https://github.com/KettleFoundation/Kettle/blob/master/patches/net/minecraft/block/BlockCake.java.patch to BlockCake.java**
Should you do this with all of the files anyways, just a guess.

**Comment by Timardo** [comment] 2019-02-28 15:28
BlockCake class is present in Kettle, but the method FoodStats.addStats() is not. If you open that link to the patch, you will see, that it's commented out. I think only the one who commented it knows why.

**Comment by GMatrixGames** [comment] 2019-03-02 18:13
It's probably managed by Bukkit, not sure though.

**Comment by Timardo** [comment] 2019-03-03 10:56
So, after a closer look into this problem I found these problems:

AppleCore is replacing the method `player.getFoodStats().addStats(2, 0.1F);` with it's own hook. There's the problem: even though the method **is** present in Kettle, it's altered to this:

https://github.com/KettleFoundation/Kettle/blob/d687b738bb2da63303a2d65e721394a3f94ee016/patches/net/minecraft/block/BlockCake.java.patch#L22

Looks alright, doesn't it? Well, not exactly, because AppleCore has this code:

https://github.com/squeek502/AppleCore/blob/2dbabf16b09527faae9107d9e8ab5b8150e03d8f/java/squeek/applecore/asm/module/ModuleBlockFood.java#L55-L56

The first line is the descriptor of the Integer of value 2 passed to the addStats() method and the second the Float one. Since the exact Integer value of 2 isn't present in the Kettle's code, AppleCore cannot find the method and throws a RuntimeException. Here you can implement CraftBukkit event handling directly to the addStats() method, which is ok (at least I think), but another [error appears](https://hastebin.com/umemikeday.rb). As I found out, this is caused by another CraftBukkit modification to the EntityPlayer class:

https://github.com/KettleFoundation/Kettle/blob/d687b738bb2da63303a2d65e721394a3f94ee016/patches/net/minecraft/entity/player/EntityPlayer.java.patch#L28-L29

AppleCore cannot find the "Forge" version of this field and throws another error. When reverted to the "Forge" version server loads fine, but when a player tries to connect [this happens](https://hastebin.com/eguxoqiweg.sql).
At this point, I really don't have enough Java knowledge to be able to continue, so it's up to @Hexeption , @aolko or another skilled java mind to fix these problems.

**Comment by josephworks** [comment] 2019-03-03 12:19
Or you can download the src, make your changes, compile, test, and pr.

**Comment by josephworks** [comment] 2019-03-03 12:23
Plus, there hasn't been a commit in 9 days, I wouldn't be expecting one anytime soon...

**Comment by kingdevnl** [comment] 2019-05-02 20:26
Please rename this issue to: AppleCore incompatible Crash

**Comment by Hexeption** [comment] 2019-05-03 10:20
Fixed in vgit-HEAD-b73f821 build

**Closed by Hexeption** 2019-05-03 10:20 UTC
Labels: bug
