### ISSUE TITLE
TARDIS Bukkit plugin

### ISSUE THREAD

**Issue by thehornydragon** [KettleFoundation/Kettle#36] opened 2019-05-28 22:30 UTC
Hello,

I've been trying to get the TARDIS Bukkit plugin to work with Kettle, but no luck, unfortunately. I've tried running this plugin on other servers that are not Bukkit, but compatible with Bukkit plugins, such as Glowstone, which throws the same error upon loading the separate TARDISChunkGenerator.jar plugin. This plugin is required, otherwise the (main) plugin will be disabled when the server is done starting. It generates the interiors. For some reason it only seems to work with the real Bukkit server (AFAIK). 

Also a big thanks for picking up where Cauldron left of with this hybrid server thing, I really like it! 

Here's the error message I got by the way (it probably helps): 

[23:17:48] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\TARDISChunkGenerator.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/EntityHuman
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[JavaPluginLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[SimplePluginManager.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [SimplePluginManager.class:git-HEAD-b7c2f7d]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:353) [CraftServer.class:git-HEAD-b7c2f7d]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:255) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:581) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201-1-ojdkbuild]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/EntityHuman
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201-1-ojdkbuild]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201-1-ojdkbuild]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:git-HEAD-b7c2f7d]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.EntityHuman
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201-1-ojdkbuild]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201-1-ojdkbuild]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201-1-ojdkbuild]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201-1-ojdkbuild]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[PluginClassLoader.class:git-HEAD-b7c2f7d]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[JavaPluginLoader.class:git-HEAD-b7c2f7d]
        ... 6 more

**Comment by RednedEpic** [comment] 2019-05-28 23:01
This is due to a lack of NMS. Which is why it would not work in other softwares such as Glowstone that only implement the Bukkit API. Hexeption was working on fixing NMS a couple weeks back if I recall correctly. As of now he is currently on vacation, so if it's not in a released version yet, it will be hopefully soon.

**Comment by josephworks** [comment] 2019-07-16 16:41
duplicate of #13

**Comment by GMatrixGames** [comment] 2019-08-20 22:00
This has been fixed in the next build!

- GMatrixGames

**Closed by GMatrixGames** 2019-08-20 22:00 UTC
Labels: KettleJava, NMS-Bug, duplicate
